siraj-samsudeen/quran-srs

main.py
utils.py

1. Fixed the 404 error that was caused by the page input on home page
2. Implemented the Bulk Edit feature with Bulk delete 
3. Fixed the date gaps in summary table
fixed #49, closed #52, fixed #50

Resolved the issues and implemented new features

---

main.py
utils.py

Implemented `mode` and `plan_id` Input fields to the Entry and Edit pages

---

main.py

Fixed the export_csv button
Resolved: #60

Implemented a route to upload DB into the `/data`

---

main.py

Updated the DB schema and refactored the code to work with `quran_v3.db`

---

main.py

- Added logic that will remove the continue link from the table based on the `completed` value in the plans table
- Added an editable link for the `plan_id` to update the status of that plan.
Closes: #58

Split the summary table based on the `mode_id` and `plan_id`

---

main.py

Implement Export/Import feature for General CRUD page

---

.gitignore
main.py
requirements.txt
utils.py

Resolved: #70 
Resolved: #71
Fixed: #72

Infinite scrolling, default values and fixed cosmetic problems

---

main.py
tests/admin.spec.ts
tests/quran_srs-test.spec.ts
tests/user_selection.spec.ts

Added switch user functionality and its playwright test

---

main.py

Fix the logic issue on the bulk and single entry pages

---

main.py

fix the export csv button in revision page

---

main.py

- Handled foreign key constraints when deleting the record
-  Fix rendering the surah name in the summary table

bump db version v6 which excluded `cascade`

---

main.py
tests/quran_srs-test.spec.ts
tests/user_management.spec.ts

cosmetic changes on the UI

---

main.py
utils.py

Create a Watch List Page

---

main.py

Create Page level memorization details

---

main.py

fix: prevent error when continuing new memorization at last page (604)

---

main.py

Add new memorization summary table to index page 

---

main.py
migrations/0006-changes-on-hafizs.sql
utils.py

Implemented close date functionality

---

main.py

fixed the home page summary table logic to update the review dates

---

main.py

- Changed the rating on the summary table from single edit form to drop-down.
- Added bulk edit link on the stats table count
- Changed the sort order of the summary table (Recent review, Watch list) based on pages(item_id)

Refactored the home page summary table

---

main.py
utils.py

- Added Total count row on the stats table
- Added logic for the checkbox and a dropdown to work both ways on the summary tables.
- Removed `record` column header for mobile spacing.

implemented these features on home page 

---

main.py
migrations/0006-changes-on-hafizs.sql
utils.py

- Changed the default rating for new memorization to `Good`
- Fixed summary filtering logic 
- Implemented a global checkbox on the summary table to select all the following checkboxes.
- Fixed: #181

Implemented the followings

---

main.py

fix: correct sort order in recently memorized pages table and update new memorization summary table display logic

---

main.py
migrations/0007-changes-on-items.sql

Resolved: #190
Introduced the `description` column on the items table

displayed the page with surah if the item has no description

---

main.py

Show daily progress for each page in both daily and weekly summary tables

---

main.py

- updated the page description in the pages of the report, new memorization, page details and the single entry form.
- Replace the Day with Reps in the summary table column
- Removed the Revision details in the hafiz selection page
- Resolved #196

Update the page description instead of the page number and surah name

---

main.py

- Fixed continuation upper limit logic.
- Changed the nav link for page_description to the page details page.
- Added `click to edit` functionality for the page_description on page details page.

fixes on continuation logic and refactored page_description behaviour

---

main.py

Implemented the summary table for monthly with action buttons to add additional rows

---

app/common_function.py
main.py

Closed: #248 
Closed: #249 
Resolved: #250

Fixed these issues

---

app/common_function.py
app/page_details.py
app/recent_review.py
app/revision.py
main.py

Resolves #254, Resolves #255, Resolves #256

Simplified the CRUD logic and Implemented confirmation page  on close date.

---

app/common_function.py
app/hafiz.py
app/page_details.py
main.py

259 fix scroll jump and `next_review` updation on full-cycle
